---
- name: Run query
  delegate_to: "{{ delegate | default('localhost') }}"
  run_query:
      config: "{{ config | default({}) }}"
      servername: "{{ servername | default('') }}"
      database: "{{ database | default('') }}"
      username: "{{ username | default('') }}"
      password: "{{ password | default('') }}"
      dbtype: "{{ dbtype | default('') }}"
      query: "{{ query | default('') }}"
      values: "{{ values | default([]) }}"
  register: run_query_output

- name: Set rows variable
  set_fact:
      query_rows: "{{ run_query_output.output }}"
