---
# tasks file for run_query
- name: Create table
  run_query:
      config: "{{ item }}"
      query: >
         create table if not exists log (
             id INT NOT NULL AUTO_INCREMENT,
             line VARCHAR(255),
             PRIMARY KEY (id)
         )

- name: Get current date
  set_fact:
      date: "{{ ansible_date_time.iso8601 }}"

- name: Insert date
  run_query:
      config: "{{ item }}"
      query: "insert into log (line) values ('{{ date }}')"

- name: Retrieve date
  run_query:
      config: "{{ item }}"
      query: "select line from log order by id desc limit 1"
  register: select

- debug:
    var: select

- debug:
    var: date

- name: Verify selection
  assert:
      that: "select.output[0].line == date"
