---
# tasks file for run_query
- name: Create table
  run_query:
      servername: "{{ item.servername }}"
      database: "{{ item.database }}"
      username: "{{ item.username }}"
      password: "{{ item.password }}"
      dbtype: "{{ item.dbtype }}"
      query: >
            if not exists (select * from sysobjects where name='log')
                create table log (
                    id int IDENTITY(1,1) PRIMARY KEY,
                    line VARCHAR(255)
                )

- name: Get current date
  set_fact:
      date: "{{ ansible_date_time.iso8601 }}"

- name: Insert date
  run_query:
      servername: "{{ item.servername }}"
      database: "{{ item.database }}"
      username: "{{ item.username }}"
      password: "{{ item.password }}"
      dbtype: "{{ item.dbtype }}"
      query: "insert into log values ('{{ date }}')"

- name: Retrieve date
  run_query:
      servername: "{{ item.servername }}"
      database: "{{ item.database }}"
      username: "{{ item.username }}"
      password: "{{ item.password }}"
      dbtype: "{{ item.dbtype }}"
      query: "select top 1 line from log order by id desc"
  register: select

- name: Verify selection
  assert:
      that: "select.output[0].line == date"
